version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pallavy
      - POSTGRES_DB=amazonish
      - POSTGRES_PASSWORD=123456789
    volumes:
      - pgdata:/var/lib/posgresql/data/amazonish
  amazonish:
    extra_hosts:
    - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis 
      - db 
    volumes:
      - .:/amazonish
  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery --app=amazonish worker --loglevel=info --logfile=logs/celery.log  
  
    volumes:
      - .:/amazonish
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - amazonish
      - redis

  redis:
    image: redis:7-alpine  
volumes:
  pgdata:
# python manage.py makemigrations && python manage.py migrate && 
#  "Mountpoint": "/var/lib/docker/volumes/httpd_logs/_data",