# Generated by Django 3.2.22 on 2023-10-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231008_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
