# Generated by Django 3.2.22 on 2023-10-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231008_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent_category', 'slug', 'name', 'description', 'tags', 'created_at', 'updated_at')},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
