# Generated by Django 3.2.22 on 2023-10-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20231022_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('category_id', 'title', 'picture', 'summary', 'description', 'price', 'discount_type', 'discount_value', 'created_at', 'updated_at')},
        ),
    ]
