# Generated by Django 3.2.22 on 2023-10-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('category_id', 'title', 'picture', 'summary', 'description', 'price', 'discount_type', 'discount_value', 'created_at', 'updated_at', 'stocks')},
        ),
        migrations.AddField(
            model_name='products',
            name='stocks',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
